/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl;

import com.btc.serviceidl.AbstractIdlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IdlRuntimeModule extends AbstractIdlRuntimeModule {
}
