/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl;

import com.btc.serviceidl.IdlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IdlStandaloneSetup extends IdlStandaloneSetupGenerated {
  public static void doSetup() {
    new IdlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
