/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ide.contentassist.antlr;

import com.btc.serviceidl.ide.contentassist.antlr.internal.InternalIdlParser;
import com.btc.serviceidl.services.IdlGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class IdlParser extends AbstractContentAssistParser {

	@Inject
	private IdlGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalIdlParser createParser() {
		InternalIdlParser result = new InternalIdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractModuleComponentAccess().getAlternatives(), "rule__AbstractModuleComponent__Alternatives");
					put(grammarAccess.getAbstractExceptionAccess().getAlternatives(), "rule__AbstractException__Alternatives");
					put(grammarAccess.getAbstractTypeDeclarationAccess().getAlternatives(), "rule__AbstractTypeDeclaration__Alternatives");
					put(grammarAccess.getAbstractCrossReferenceAccess().getAlternatives(), "rule__AbstractCrossReference__Alternatives");
					put(grammarAccess.getAbstractTypeAccess().getAlternatives(), "rule__AbstractType__Alternatives");
					put(grammarAccess.getAbstractCollectionAccess().getAlternatives(), "rule__AbstractCollection__Alternatives");
					put(grammarAccess.getSequenceDeclarationAccess().getAlternatives_2(), "rule__SequenceDeclaration__Alternatives_2");
					put(grammarAccess.getAbstractSequenceHintAccess().getAlternatives(), "rule__AbstractSequenceHint__Alternatives");
					put(grammarAccess.getStructDeclarationAccess().getAlternatives_4_0(), "rule__StructDeclaration__Alternatives_4_0");
					put(grammarAccess.getAbstractInterfaceComponentAccess().getAlternatives(), "rule__AbstractInterfaceComponent__Alternatives");
					put(grammarAccess.getReturnTypeElementAccess().getAlternatives(), "rule__ReturnTypeElement__Alternatives");
					put(grammarAccess.getDocCommentElementAccess().getTextAlternatives_0(), "rule__DocCommentElement__TextAlternatives_0");
					put(grammarAccess.getPrimitiveTypeAccess().getAlternatives(), "rule__PrimitiveType__Alternatives");
					put(grammarAccess.getIntegerTypeAccess().getAlternatives(), "rule__IntegerType__Alternatives");
					put(grammarAccess.getFloatingPointTypeAccess().getAlternatives(), "rule__FloatingPointType__Alternatives");
					put(grammarAccess.getParameterDirectionAccess().getAlternatives(), "rule__ParameterDirection__Alternatives");
					put(grammarAccess.getIDLSpecificationAccess().getGroup(), "rule__IDLSpecification__Group__0");
					put(grammarAccess.getImportDeclarationAccess().getGroup(), "rule__ImportDeclaration__Group__0");
					put(grammarAccess.getModuleDeclarationAccess().getGroup(), "rule__ModuleDeclaration__Group__0");
					put(grammarAccess.getAbstractModuleComponentAccess().getGroup_0(), "rule__AbstractModuleComponent__Group_0__0");
					put(grammarAccess.getAbstractModuleComponentAccess().getGroup_1(), "rule__AbstractModuleComponent__Group_1__0");
					put(grammarAccess.getAbstractModuleComponentAccess().getGroup_2(), "rule__AbstractModuleComponent__Group_2__0");
					put(grammarAccess.getAbstractModuleComponentAccess().getGroup_3(), "rule__AbstractModuleComponent__Group_3__0");
					put(grammarAccess.getAbstractModuleComponentAccess().getGroup_4(), "rule__AbstractModuleComponent__Group_4__0");
					put(grammarAccess.getExceptionReferenceDeclarationAccess().getGroup(), "rule__ExceptionReferenceDeclaration__Group__0");
					put(grammarAccess.getExceptionDeclarationAccess().getGroup(), "rule__ExceptionDeclaration__Group__0");
					put(grammarAccess.getExceptionDeclarationAccess().getGroup_2(), "rule__ExceptionDeclaration__Group_2__0");
					put(grammarAccess.getExceptionDeclarationAccess().getGroup_4(), "rule__ExceptionDeclaration__Group_4__0");
					put(grammarAccess.getAliasDeclarationAccess().getGroup(), "rule__AliasDeclaration__Group__0");
					put(grammarAccess.getEnumDeclarationAccess().getGroup(), "rule__EnumDeclaration__Group__0");
					put(grammarAccess.getEnumDeclarationAccess().getGroup_4(), "rule__EnumDeclaration__Group_4__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup(), "rule__SequenceDeclaration__Group__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup_2_1(), "rule__SequenceDeclaration__Group_2_1__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup_2_1_2(), "rule__SequenceDeclaration__Group_2_1_2__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup_2_1_2_2(), "rule__SequenceDeclaration__Group_2_1_2_2__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup_4(), "rule__SequenceDeclaration__Group_4__0");
					put(grammarAccess.getSequenceDeclarationAccess().getGroup_4_2(), "rule__SequenceDeclaration__Group_4_2__0");
					put(grammarAccess.getTypicalLengthHintAccess().getGroup(), "rule__TypicalLengthHint__Group__0");
					put(grammarAccess.getTypicalSizeHintAccess().getGroup(), "rule__TypicalSizeHint__Group__0");
					put(grammarAccess.getTupleDeclarationAccess().getGroup(), "rule__TupleDeclaration__Group__0");
					put(grammarAccess.getTupleDeclarationAccess().getGroup_3(), "rule__TupleDeclaration__Group_3__0");
					put(grammarAccess.getStructDeclarationAccess().getGroup(), "rule__StructDeclaration__Group__0");
					put(grammarAccess.getStructDeclarationAccess().getGroup_2(), "rule__StructDeclaration__Group_2__0");
					put(grammarAccess.getStructDeclarationAccess().getGroup_4(), "rule__StructDeclaration__Group_4__0");
					put(grammarAccess.getMemberElementAccess().getGroup(), "rule__MemberElement__Group__0");
					put(grammarAccess.getKeyElementAccess().getGroup(), "rule__KeyElement__Group__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup(), "rule__InterfaceDeclaration__Group__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup_4(), "rule__InterfaceDeclaration__Group_4__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup_4_1_0(), "rule__InterfaceDeclaration__Group_4_1_0__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup_4_1_1(), "rule__InterfaceDeclaration__Group_4_1_1__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup_5(), "rule__InterfaceDeclaration__Group_5__0");
					put(grammarAccess.getInterfaceDeclarationAccess().getGroup_5_2(), "rule__InterfaceDeclaration__Group_5_2__0");
					put(grammarAccess.getAbstractInterfaceComponentAccess().getGroup_0(), "rule__AbstractInterfaceComponent__Group_0__0");
					put(grammarAccess.getAbstractInterfaceComponentAccess().getGroup_1(), "rule__AbstractInterfaceComponent__Group_1__0");
					put(grammarAccess.getAbstractInterfaceComponentAccess().getGroup_2(), "rule__AbstractInterfaceComponent__Group_2__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_5(), "rule__FunctionDeclaration__Group_5__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_5_1(), "rule__FunctionDeclaration__Group_5_1__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_7(), "rule__FunctionDeclaration__Group_7__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_7_0(), "rule__FunctionDeclaration__Group_7_0__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_7_1(), "rule__FunctionDeclaration__Group_7_1__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_7_1_2(), "rule__FunctionDeclaration__Group_7_1_2__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup(), "rule__EventDeclaration__Group__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_2(), "rule__EventDeclaration__Group_2__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_2_1(), "rule__EventDeclaration__Group_2_1__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6(), "rule__EventDeclaration__Group_6__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6_0(), "rule__EventDeclaration__Group_6_0__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6_0_3(), "rule__EventDeclaration__Group_6_0_3__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6_0_3_1(), "rule__EventDeclaration__Group_6_0_3_1__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6_1(), "rule__EventDeclaration__Group_6_1__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_6_1_2(), "rule__EventDeclaration__Group_6_1_2__0");
					put(grammarAccess.getParameterElementAccess().getGroup(), "rule__ParameterElement__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getIDLSpecificationAccess().getImportedEntitiesAssignment_0(), "rule__IDLSpecification__ImportedEntitiesAssignment_0");
					put(grammarAccess.getIDLSpecificationAccess().getModulesAssignment_1(), "rule__IDLSpecification__ModulesAssignment_1");
					put(grammarAccess.getImportDeclarationAccess().getImportedNamespaceAssignment_1(), "rule__ImportDeclaration__ImportedNamespaceAssignment_1");
					put(grammarAccess.getModuleDeclarationAccess().getVirtualAssignment_0(), "rule__ModuleDeclaration__VirtualAssignment_0");
					put(grammarAccess.getModuleDeclarationAccess().getMainAssignment_1(), "rule__ModuleDeclaration__MainAssignment_1");
					put(grammarAccess.getModuleDeclarationAccess().getNameAssignment_3(), "rule__ModuleDeclaration__NameAssignment_3");
					put(grammarAccess.getModuleDeclarationAccess().getModuleComponentsAssignment_5(), "rule__ModuleDeclaration__ModuleComponentsAssignment_5");
					put(grammarAccess.getModuleDeclarationAccess().getNestedModulesAssignment_6(), "rule__ModuleDeclaration__NestedModulesAssignment_6");
					put(grammarAccess.getExceptionReferenceDeclarationAccess().getNameAssignment_1(), "rule__ExceptionReferenceDeclaration__NameAssignment_1");
					put(grammarAccess.getExceptionReferenceDeclarationAccess().getLocationAssignment_3(), "rule__ExceptionReferenceDeclaration__LocationAssignment_3");
					put(grammarAccess.getExceptionDeclarationAccess().getNameAssignment_1(), "rule__ExceptionDeclaration__NameAssignment_1");
					put(grammarAccess.getExceptionDeclarationAccess().getSupertypeAssignment_2_1(), "rule__ExceptionDeclaration__SupertypeAssignment_2_1");
					put(grammarAccess.getExceptionDeclarationAccess().getMembersAssignment_4_0(), "rule__ExceptionDeclaration__MembersAssignment_4_0");
					put(grammarAccess.getAbstractTypeAccess().getPrimitiveTypeAssignment_0(), "rule__AbstractType__PrimitiveTypeAssignment_0");
					put(grammarAccess.getAbstractTypeAccess().getReferenceTypeAssignment_1(), "rule__AbstractType__ReferenceTypeAssignment_1");
					put(grammarAccess.getAbstractTypeAccess().getCollectionTypeAssignment_2(), "rule__AbstractType__CollectionTypeAssignment_2");
					put(grammarAccess.getAliasDeclarationAccess().getTypeAssignment_1(), "rule__AliasDeclaration__TypeAssignment_1");
					put(grammarAccess.getAliasDeclarationAccess().getNameAssignment_2(), "rule__AliasDeclaration__NameAssignment_2");
					put(grammarAccess.getEnumDeclarationAccess().getNameAssignment_1(), "rule__EnumDeclaration__NameAssignment_1");
					put(grammarAccess.getEnumDeclarationAccess().getContainedIdentifiersAssignment_3(), "rule__EnumDeclaration__ContainedIdentifiersAssignment_3");
					put(grammarAccess.getEnumDeclarationAccess().getContainedIdentifiersAssignment_4_1(), "rule__EnumDeclaration__ContainedIdentifiersAssignment_4_1");
					put(grammarAccess.getEnumDeclarationAccess().getDeclaratorAssignment_6(), "rule__EnumDeclaration__DeclaratorAssignment_6");
					put(grammarAccess.getSequenceDeclarationAccess().getTypeAssignment_2_0(), "rule__SequenceDeclaration__TypeAssignment_2_0");
					put(grammarAccess.getSequenceDeclarationAccess().getFailableAssignment_2_1_0(), "rule__SequenceDeclaration__FailableAssignment_2_1_0");
					put(grammarAccess.getSequenceDeclarationAccess().getTypeAssignment_2_1_1(), "rule__SequenceDeclaration__TypeAssignment_2_1_1");
					put(grammarAccess.getSequenceDeclarationAccess().getRaisedExceptionsAssignment_2_1_2_1(), "rule__SequenceDeclaration__RaisedExceptionsAssignment_2_1_2_1");
					put(grammarAccess.getSequenceDeclarationAccess().getRaisedExceptionsAssignment_2_1_2_2_1(), "rule__SequenceDeclaration__RaisedExceptionsAssignment_2_1_2_2_1");
					put(grammarAccess.getSequenceDeclarationAccess().getSequenceHintsAssignment_4_1(), "rule__SequenceDeclaration__SequenceHintsAssignment_4_1");
					put(grammarAccess.getSequenceDeclarationAccess().getSequenceHintsAssignment_4_2_1(), "rule__SequenceDeclaration__SequenceHintsAssignment_4_2_1");
					put(grammarAccess.getTypicalLengthHintAccess().getLengthAssignment_4(), "rule__TypicalLengthHint__LengthAssignment_4");
					put(grammarAccess.getTypicalSizeHintAccess().getSizeAssignment_4(), "rule__TypicalSizeHint__SizeAssignment_4");
					put(grammarAccess.getTupleDeclarationAccess().getTypesAssignment_2(), "rule__TupleDeclaration__TypesAssignment_2");
					put(grammarAccess.getTupleDeclarationAccess().getTypesAssignment_3_1(), "rule__TupleDeclaration__TypesAssignment_3_1");
					put(grammarAccess.getStructDeclarationAccess().getNameAssignment_1(), "rule__StructDeclaration__NameAssignment_1");
					put(grammarAccess.getStructDeclarationAccess().getSupertypeAssignment_2_1(), "rule__StructDeclaration__SupertypeAssignment_2_1");
					put(grammarAccess.getStructDeclarationAccess().getMembersAssignment_4_0_0(), "rule__StructDeclaration__MembersAssignment_4_0_0");
					put(grammarAccess.getStructDeclarationAccess().getTypeDeclsAssignment_4_0_1(), "rule__StructDeclaration__TypeDeclsAssignment_4_0_1");
					put(grammarAccess.getStructDeclarationAccess().getDeclaratorAssignment_6(), "rule__StructDeclaration__DeclaratorAssignment_6");
					put(grammarAccess.getMemberElementAccess().getOptionalAssignment_0(), "rule__MemberElement__OptionalAssignment_0");
					put(grammarAccess.getMemberElementAccess().getTypeAssignment_1(), "rule__MemberElement__TypeAssignment_1");
					put(grammarAccess.getMemberElementAccess().getNameAssignment_2(), "rule__MemberElement__NameAssignment_2");
					put(grammarAccess.getKeyElementAccess().getTypeAssignment_0(), "rule__KeyElement__TypeAssignment_0");
					put(grammarAccess.getKeyElementAccess().getKeyNameAssignment_1(), "rule__KeyElement__KeyNameAssignment_1");
					put(grammarAccess.getInterfaceDeclarationAccess().getDocCommentsAssignment_0(), "rule__InterfaceDeclaration__DocCommentsAssignment_0");
					put(grammarAccess.getInterfaceDeclarationAccess().getAbstractAssignment_1(), "rule__InterfaceDeclaration__AbstractAssignment_1");
					put(grammarAccess.getInterfaceDeclarationAccess().getNameAssignment_3(), "rule__InterfaceDeclaration__NameAssignment_3");
					put(grammarAccess.getInterfaceDeclarationAccess().getVersionAssignment_4_1_0_2(), "rule__InterfaceDeclaration__VersionAssignment_4_1_0_2");
					put(grammarAccess.getInterfaceDeclarationAccess().getGuidAssignment_4_1_1_2(), "rule__InterfaceDeclaration__GuidAssignment_4_1_1_2");
					put(grammarAccess.getInterfaceDeclarationAccess().getDerivesFromAssignment_5_1(), "rule__InterfaceDeclaration__DerivesFromAssignment_5_1");
					put(grammarAccess.getInterfaceDeclarationAccess().getDerivesFromAssignment_5_2_1(), "rule__InterfaceDeclaration__DerivesFromAssignment_5_2_1");
					put(grammarAccess.getInterfaceDeclarationAccess().getContainsAssignment_7(), "rule__InterfaceDeclaration__ContainsAssignment_7");
					put(grammarAccess.getFunctionDeclarationAccess().getDocCommentsAssignment_0(), "rule__FunctionDeclaration__DocCommentsAssignment_0");
					put(grammarAccess.getFunctionDeclarationAccess().getSyncAssignment_1(), "rule__FunctionDeclaration__SyncAssignment_1");
					put(grammarAccess.getFunctionDeclarationAccess().getQueryAssignment_2(), "rule__FunctionDeclaration__QueryAssignment_2");
					put(grammarAccess.getFunctionDeclarationAccess().getNameAssignment_3(), "rule__FunctionDeclaration__NameAssignment_3");
					put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_5_0(), "rule__FunctionDeclaration__ParametersAssignment_5_0");
					put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_5_1_1(), "rule__FunctionDeclaration__ParametersAssignment_5_1_1");
					put(grammarAccess.getFunctionDeclarationAccess().getInjectedAssignment_7_0_1(), "rule__FunctionDeclaration__InjectedAssignment_7_0_1");
					put(grammarAccess.getFunctionDeclarationAccess().getReturnedTypeAssignment_7_0_2(), "rule__FunctionDeclaration__ReturnedTypeAssignment_7_0_2");
					put(grammarAccess.getFunctionDeclarationAccess().getRaisedExceptionsAssignment_7_1_1(), "rule__FunctionDeclaration__RaisedExceptionsAssignment_7_1_1");
					put(grammarAccess.getFunctionDeclarationAccess().getRaisedExceptionsAssignment_7_1_2_1(), "rule__FunctionDeclaration__RaisedExceptionsAssignment_7_1_2_1");
					put(grammarAccess.getEventDeclarationAccess().getNameAssignment_1(), "rule__EventDeclaration__NameAssignment_1");
					put(grammarAccess.getEventDeclarationAccess().getGuidAssignment_2_1_2(), "rule__EventDeclaration__GuidAssignment_2_1_2");
					put(grammarAccess.getEventDeclarationAccess().getDataAssignment_4(), "rule__EventDeclaration__DataAssignment_4");
					put(grammarAccess.getEventDeclarationAccess().getKeysAssignment_6_0_3_0(), "rule__EventDeclaration__KeysAssignment_6_0_3_0");
					put(grammarAccess.getEventDeclarationAccess().getKeysAssignment_6_0_3_1_1(), "rule__EventDeclaration__KeysAssignment_6_0_3_1_1");
					put(grammarAccess.getEventDeclarationAccess().getRaisedExceptionsAssignment_6_1_1(), "rule__EventDeclaration__RaisedExceptionsAssignment_6_1_1");
					put(grammarAccess.getEventDeclarationAccess().getRaisedExceptionsAssignment_6_1_2_1(), "rule__EventDeclaration__RaisedExceptionsAssignment_6_1_2_1");
					put(grammarAccess.getReturnTypeElementAccess().getVoidAssignment_1(), "rule__ReturnTypeElement__VoidAssignment_1");
					put(grammarAccess.getParameterElementAccess().getDirectionAssignment_0(), "rule__ParameterElement__DirectionAssignment_0");
					put(grammarAccess.getParameterElementAccess().getParamTypeAssignment_1(), "rule__ParameterElement__ParamTypeAssignment_1");
					put(grammarAccess.getParameterElementAccess().getParamNameAssignment_2(), "rule__ParameterElement__ParamNameAssignment_2");
					put(grammarAccess.getDocCommentElementAccess().getTextAssignment(), "rule__DocCommentElement__TextAssignment");
					put(grammarAccess.getPrimitiveTypeAccess().getIntegerTypeAssignment_0(), "rule__PrimitiveType__IntegerTypeAssignment_0");
					put(grammarAccess.getPrimitiveTypeAccess().getStringTypeAssignment_1(), "rule__PrimitiveType__StringTypeAssignment_1");
					put(grammarAccess.getPrimitiveTypeAccess().getCharTypeAssignment_2(), "rule__PrimitiveType__CharTypeAssignment_2");
					put(grammarAccess.getPrimitiveTypeAccess().getFloatingPointTypeAssignment_3(), "rule__PrimitiveType__FloatingPointTypeAssignment_3");
					put(grammarAccess.getPrimitiveTypeAccess().getUuidTypeAssignment_4(), "rule__PrimitiveType__UuidTypeAssignment_4");
					put(grammarAccess.getPrimitiveTypeAccess().getBooleanTypeAssignment_5(), "rule__PrimitiveType__BooleanTypeAssignment_5");
					put(grammarAccess.getInterfaceDeclarationAccess().getUnorderedGroup_4_1(), "rule__InterfaceDeclaration__UnorderedGroup_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
