/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIdlScopeProvider extends DelegatingScopeProvider {
}
