/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Type Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getAbstractTypeDeclaration()
 * @model
 * @generated
 */
public interface AbstractTypeDeclaration extends AbstractInterfaceComponent
{
} // AbstractTypeDeclaration
