/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Interface Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getAbstractInterfaceComponent()
 * @model
 * @generated
 */
public interface AbstractInterfaceComponent extends EObject
{
} // AbstractInterfaceComponent
