/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Collection</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getAbstractCollection()
 * @model
 * @generated
 */
public interface AbstractCollection extends AbstractCrossReference
{
} // AbstractCollection
