/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.EventDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.EventDeclaration#getGuid <em>Guid</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.EventDeclaration#getData <em>Data</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.EventDeclaration#getKeys <em>Keys</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.EventDeclaration#getRaisedExceptions <em>Raised Exceptions</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration()
 * @model
 * @generated
 */
public interface EventDeclaration extends AbstractInterfaceComponent
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.EventDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Guid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guid</em>' attribute.
   * @see #setGuid(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration_Guid()
   * @model
   * @generated
   */
  String getGuid();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.EventDeclaration#getGuid <em>Guid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guid</em>' attribute.
   * @see #getGuid()
   * @generated
   */
  void setGuid(String value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' reference.
   * @see #setData(StructDeclaration)
   * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration_Data()
   * @model
   * @generated
   */
  StructDeclaration getData();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.EventDeclaration#getData <em>Data</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' reference.
   * @see #getData()
   * @generated
   */
  void setData(StructDeclaration value);

  /**
   * Returns the value of the '<em><b>Keys</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.KeyElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keys</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration_Keys()
   * @model containment="true"
   * @generated
   */
  EList<KeyElement> getKeys();

  /**
   * Returns the value of the '<em><b>Raised Exceptions</b></em>' reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.AbstractException}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Raised Exceptions</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Raised Exceptions</em>' reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getEventDeclaration_RaisedExceptions()
   * @model
   * @generated
   */
  EList<AbstractException> getRaisedExceptions();

} // EventDeclaration
