/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exception Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.ExceptionDeclaration#getSupertype <em>Supertype</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ExceptionDeclaration#getMembers <em>Members</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getExceptionDeclaration()
 * @model
 * @generated
 */
public interface ExceptionDeclaration extends AbstractException
{
  /**
   * Returns the value of the '<em><b>Supertype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Supertype</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Supertype</em>' reference.
   * @see #setSupertype(AbstractException)
   * @see com.btc.serviceidl.idl.IdlPackage#getExceptionDeclaration_Supertype()
   * @model
   * @generated
   */
  AbstractException getSupertype();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ExceptionDeclaration#getSupertype <em>Supertype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Supertype</em>' reference.
   * @see #getSupertype()
   * @generated
   */
  void setSupertype(AbstractException value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.MemberElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getExceptionDeclaration_Members()
   * @model containment="true"
   * @generated
   */
  EList<MemberElement> getMembers();

} // ExceptionDeclaration
