/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#getDocComments <em>Doc Comments</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#isSync <em>Sync</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#isQuery <em>Query</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#getParameters <em>Parameters</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#isInjected <em>Injected</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#getReturnedType <em>Returned Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.FunctionDeclaration#getRaisedExceptions <em>Raised Exceptions</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration()
 * @model
 * @generated
 */
public interface FunctionDeclaration extends AbstractInterfaceComponent
{
  /**
   * Returns the value of the '<em><b>Doc Comments</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.DocCommentElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Doc Comments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Doc Comments</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_DocComments()
   * @model containment="true"
   * @generated
   */
  EList<DocCommentElement> getDocComments();

  /**
   * Returns the value of the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sync</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sync</em>' attribute.
   * @see #setSync(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_Sync()
   * @model
   * @generated
   */
  boolean isSync();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.FunctionDeclaration#isSync <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sync</em>' attribute.
   * @see #isSync()
   * @generated
   */
  void setSync(boolean value);

  /**
   * Returns the value of the '<em><b>Query</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' attribute.
   * @see #setQuery(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_Query()
   * @model
   * @generated
   */
  boolean isQuery();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.FunctionDeclaration#isQuery <em>Query</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' attribute.
   * @see #isQuery()
   * @generated
   */
  void setQuery(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.FunctionDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.ParameterElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<ParameterElement> getParameters();

  /**
   * Returns the value of the '<em><b>Injected</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Injected</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Injected</em>' attribute.
   * @see #setInjected(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_Injected()
   * @model
   * @generated
   */
  boolean isInjected();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.FunctionDeclaration#isInjected <em>Injected</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Injected</em>' attribute.
   * @see #isInjected()
   * @generated
   */
  void setInjected(boolean value);

  /**
   * Returns the value of the '<em><b>Returned Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Returned Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Returned Type</em>' containment reference.
   * @see #setReturnedType(ReturnTypeElement)
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_ReturnedType()
   * @model containment="true"
   * @generated
   */
  ReturnTypeElement getReturnedType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.FunctionDeclaration#getReturnedType <em>Returned Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Returned Type</em>' containment reference.
   * @see #getReturnedType()
   * @generated
   */
  void setReturnedType(ReturnTypeElement value);

  /**
   * Returns the value of the '<em><b>Raised Exceptions</b></em>' reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.AbstractException}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Raised Exceptions</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Raised Exceptions</em>' reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getFunctionDeclaration_RaisedExceptions()
   * @model
   * @generated
   */
  EList<AbstractException> getRaisedExceptions();

} // FunctionDeclaration
