/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.btc.serviceidl.idl.IdlPackage
 * @generated
 */
public interface IdlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IdlFactory eINSTANCE = com.btc.serviceidl.idl.impl.IdlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>IDL Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>IDL Specification</em>'.
   * @generated
   */
  IDLSpecification createIDLSpecification();

  /**
   * Returns a new object of class '<em>Import Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Declaration</em>'.
   * @generated
   */
  ImportDeclaration createImportDeclaration();

  /**
   * Returns a new object of class '<em>Module Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Module Declaration</em>'.
   * @generated
   */
  ModuleDeclaration createModuleDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Module Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Module Component</em>'.
   * @generated
   */
  AbstractModuleComponent createAbstractModuleComponent();

  /**
   * Returns a new object of class '<em>Abstract Exception</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Exception</em>'.
   * @generated
   */
  AbstractException createAbstractException();

  /**
   * Returns a new object of class '<em>Exception Reference Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exception Reference Declaration</em>'.
   * @generated
   */
  ExceptionReferenceDeclaration createExceptionReferenceDeclaration();

  /**
   * Returns a new object of class '<em>Exception Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exception Declaration</em>'.
   * @generated
   */
  ExceptionDeclaration createExceptionDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Type Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Type Declaration</em>'.
   * @generated
   */
  AbstractTypeDeclaration createAbstractTypeDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Cross Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Cross Reference</em>'.
   * @generated
   */
  AbstractCrossReference createAbstractCrossReference();

  /**
   * Returns a new object of class '<em>Abstract Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Type</em>'.
   * @generated
   */
  AbstractType createAbstractType();

  /**
   * Returns a new object of class '<em>Alias Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alias Declaration</em>'.
   * @generated
   */
  AliasDeclaration createAliasDeclaration();

  /**
   * Returns a new object of class '<em>Enum Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Declaration</em>'.
   * @generated
   */
  EnumDeclaration createEnumDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Collection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Collection</em>'.
   * @generated
   */
  AbstractCollection createAbstractCollection();

  /**
   * Returns a new object of class '<em>Sequence Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sequence Declaration</em>'.
   * @generated
   */
  SequenceDeclaration createSequenceDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Sequence Hint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Sequence Hint</em>'.
   * @generated
   */
  AbstractSequenceHint createAbstractSequenceHint();

  /**
   * Returns a new object of class '<em>Typical Length Hint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Typical Length Hint</em>'.
   * @generated
   */
  TypicalLengthHint createTypicalLengthHint();

  /**
   * Returns a new object of class '<em>Typical Size Hint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Typical Size Hint</em>'.
   * @generated
   */
  TypicalSizeHint createTypicalSizeHint();

  /**
   * Returns a new object of class '<em>Tuple Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tuple Declaration</em>'.
   * @generated
   */
  TupleDeclaration createTupleDeclaration();

  /**
   * Returns a new object of class '<em>Struct Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Struct Declaration</em>'.
   * @generated
   */
  StructDeclaration createStructDeclaration();

  /**
   * Returns a new object of class '<em>Member Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Member Element</em>'.
   * @generated
   */
  MemberElement createMemberElement();

  /**
   * Returns a new object of class '<em>Key Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Key Element</em>'.
   * @generated
   */
  KeyElement createKeyElement();

  /**
   * Returns a new object of class '<em>Interface Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Interface Declaration</em>'.
   * @generated
   */
  InterfaceDeclaration createInterfaceDeclaration();

  /**
   * Returns a new object of class '<em>Abstract Interface Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Interface Component</em>'.
   * @generated
   */
  AbstractInterfaceComponent createAbstractInterfaceComponent();

  /**
   * Returns a new object of class '<em>Function Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Declaration</em>'.
   * @generated
   */
  FunctionDeclaration createFunctionDeclaration();

  /**
   * Returns a new object of class '<em>Event Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Declaration</em>'.
   * @generated
   */
  EventDeclaration createEventDeclaration();

  /**
   * Returns a new object of class '<em>Return Type Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Return Type Element</em>'.
   * @generated
   */
  ReturnTypeElement createReturnTypeElement();

  /**
   * Returns a new object of class '<em>Parameter Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parameter Element</em>'.
   * @generated
   */
  ParameterElement createParameterElement();

  /**
   * Returns a new object of class '<em>Doc Comment Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Doc Comment Element</em>'.
   * @generated
   */
  DocCommentElement createDocCommentElement();

  /**
   * Returns a new object of class '<em>Primitive Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primitive Type</em>'.
   * @generated
   */
  PrimitiveType createPrimitiveType();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  IdlPackage getIdlPackage();

} //IdlFactory
