/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IDL Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.IDLSpecification#getImportedEntities <em>Imported Entities</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.IDLSpecification#getModules <em>Modules</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getIDLSpecification()
 * @model
 * @generated
 */
public interface IDLSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Imported Entities</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.ImportDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imported Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imported Entities</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getIDLSpecification_ImportedEntities()
   * @model containment="true"
   * @generated
   */
  EList<ImportDeclaration> getImportedEntities();

  /**
   * Returns the value of the '<em><b>Modules</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.ModuleDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Modules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modules</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getIDLSpecification_Modules()
   * @model containment="true"
   * @generated
   */
  EList<ModuleDeclaration> getModules();

} // IDLSpecification
