/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.ModuleDeclaration#isVirtual <em>Virtual</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ModuleDeclaration#isMain <em>Main</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ModuleDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ModuleDeclaration#getModuleComponents <em>Module Components</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ModuleDeclaration#getNestedModules <em>Nested Modules</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration()
 * @model
 * @generated
 */
public interface ModuleDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Virtual</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Virtual</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Virtual</em>' attribute.
   * @see #setVirtual(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration_Virtual()
   * @model
   * @generated
   */
  boolean isVirtual();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ModuleDeclaration#isVirtual <em>Virtual</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Virtual</em>' attribute.
   * @see #isVirtual()
   * @generated
   */
  void setVirtual(boolean value);

  /**
   * Returns the value of the '<em><b>Main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Main</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main</em>' attribute.
   * @see #setMain(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration_Main()
   * @model
   * @generated
   */
  boolean isMain();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ModuleDeclaration#isMain <em>Main</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main</em>' attribute.
   * @see #isMain()
   * @generated
   */
  void setMain(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ModuleDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Module Components</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.AbstractModuleComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Module Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module Components</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration_ModuleComponents()
   * @model containment="true"
   * @generated
   */
  EList<AbstractModuleComponent> getModuleComponents();

  /**
   * Returns the value of the '<em><b>Nested Modules</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.ModuleDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nested Modules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Modules</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getModuleDeclaration_NestedModules()
   * @model containment="true"
   * @generated
   */
  EList<ModuleDeclaration> getNestedModules();

} // ModuleDeclaration
