/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.ParameterElement#getDirection <em>Direction</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ParameterElement#getParamType <em>Param Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.ParameterElement#getParamName <em>Param Name</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getParameterElement()
 * @model
 * @generated
 */
public interface ParameterElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Direction</b></em>' attribute.
   * The literals are from the enumeration {@link com.btc.serviceidl.idl.ParameterDirection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direction</em>' attribute.
   * @see com.btc.serviceidl.idl.ParameterDirection
   * @see #setDirection(ParameterDirection)
   * @see com.btc.serviceidl.idl.IdlPackage#getParameterElement_Direction()
   * @model
   * @generated
   */
  ParameterDirection getDirection();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ParameterElement#getDirection <em>Direction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direction</em>' attribute.
   * @see com.btc.serviceidl.idl.ParameterDirection
   * @see #getDirection()
   * @generated
   */
  void setDirection(ParameterDirection value);

  /**
   * Returns the value of the '<em><b>Param Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Type</em>' containment reference.
   * @see #setParamType(AbstractType)
   * @see com.btc.serviceidl.idl.IdlPackage#getParameterElement_ParamType()
   * @model containment="true"
   * @generated
   */
  AbstractType getParamType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ParameterElement#getParamType <em>Param Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Type</em>' containment reference.
   * @see #getParamType()
   * @generated
   */
  void setParamType(AbstractType value);

  /**
   * Returns the value of the '<em><b>Param Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Name</em>' attribute.
   * @see #setParamName(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getParameterElement_ParamName()
   * @model
   * @generated
   */
  String getParamName();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ParameterElement#getParamName <em>Param Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param Name</em>' attribute.
   * @see #getParamName()
   * @generated
   */
  void setParamName(String value);

} // ParameterElement
