/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getIntegerType <em>Integer Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getStringType <em>String Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getCharType <em>Char Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getFloatingPointType <em>Floating Point Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getUuidType <em>Uuid Type</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.PrimitiveType#getBooleanType <em>Boolean Type</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType()
 * @model
 * @generated
 */
public interface PrimitiveType extends EObject
{
  /**
   * Returns the value of the '<em><b>Integer Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Integer Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer Type</em>' attribute.
   * @see #setIntegerType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_IntegerType()
   * @model
   * @generated
   */
  String getIntegerType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getIntegerType <em>Integer Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer Type</em>' attribute.
   * @see #getIntegerType()
   * @generated
   */
  void setIntegerType(String value);

  /**
   * Returns the value of the '<em><b>String Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String Type</em>' attribute.
   * @see #setStringType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_StringType()
   * @model
   * @generated
   */
  String getStringType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getStringType <em>String Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String Type</em>' attribute.
   * @see #getStringType()
   * @generated
   */
  void setStringType(String value);

  /**
   * Returns the value of the '<em><b>Char Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Char Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Char Type</em>' attribute.
   * @see #setCharType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_CharType()
   * @model
   * @generated
   */
  String getCharType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getCharType <em>Char Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Char Type</em>' attribute.
   * @see #getCharType()
   * @generated
   */
  void setCharType(String value);

  /**
   * Returns the value of the '<em><b>Floating Point Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Floating Point Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Floating Point Type</em>' attribute.
   * @see #setFloatingPointType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_FloatingPointType()
   * @model
   * @generated
   */
  String getFloatingPointType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getFloatingPointType <em>Floating Point Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Floating Point Type</em>' attribute.
   * @see #getFloatingPointType()
   * @generated
   */
  void setFloatingPointType(String value);

  /**
   * Returns the value of the '<em><b>Uuid Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Uuid Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uuid Type</em>' attribute.
   * @see #setUuidType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_UuidType()
   * @model
   * @generated
   */
  String getUuidType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getUuidType <em>Uuid Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uuid Type</em>' attribute.
   * @see #getUuidType()
   * @generated
   */
  void setUuidType(String value);

  /**
   * Returns the value of the '<em><b>Boolean Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Boolean Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean Type</em>' attribute.
   * @see #setBooleanType(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getPrimitiveType_BooleanType()
   * @model
   * @generated
   */
  String getBooleanType();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.PrimitiveType#getBooleanType <em>Boolean Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean Type</em>' attribute.
   * @see #getBooleanType()
   * @generated
   */
  void setBooleanType(String value);

} // PrimitiveType
