/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return Type Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.ReturnTypeElement#isVoid <em>Void</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getReturnTypeElement()
 * @model
 * @generated
 */
public interface ReturnTypeElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Void</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Void</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Void</em>' attribute.
   * @see #setVoid(boolean)
   * @see com.btc.serviceidl.idl.IdlPackage#getReturnTypeElement_Void()
   * @model
   * @generated
   */
  boolean isVoid();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.ReturnTypeElement#isVoid <em>Void</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Void</em>' attribute.
   * @see #isVoid()
   * @generated
   */
  void setVoid(boolean value);

} // ReturnTypeElement
