/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Struct Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.StructDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.StructDeclaration#getSupertype <em>Supertype</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.StructDeclaration#getMembers <em>Members</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.StructDeclaration#getTypeDecls <em>Type Decls</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.StructDeclaration#getDeclarator <em>Declarator</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration()
 * @model
 * @generated
 */
public interface StructDeclaration extends AbstractModuleComponent, AbstractTypeDeclaration, AbstractCrossReference
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.StructDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Supertype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Supertype</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Supertype</em>' reference.
   * @see #setSupertype(StructDeclaration)
   * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration_Supertype()
   * @model
   * @generated
   */
  StructDeclaration getSupertype();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.StructDeclaration#getSupertype <em>Supertype</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Supertype</em>' reference.
   * @see #getSupertype()
   * @generated
   */
  void setSupertype(StructDeclaration value);

  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.MemberElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Members</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration_Members()
   * @model containment="true"
   * @generated
   */
  EList<MemberElement> getMembers();

  /**
   * Returns the value of the '<em><b>Type Decls</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.AbstractTypeDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Decls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Decls</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration_TypeDecls()
   * @model containment="true"
   * @generated
   */
  EList<AbstractTypeDeclaration> getTypeDecls();

  /**
   * Returns the value of the '<em><b>Declarator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarator</em>' attribute.
   * @see #setDeclarator(String)
   * @see com.btc.serviceidl.idl.IdlPackage#getStructDeclaration_Declarator()
   * @model
   * @generated
   */
  String getDeclarator();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.StructDeclaration#getDeclarator <em>Declarator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declarator</em>' attribute.
   * @see #getDeclarator()
   * @generated
   */
  void setDeclarator(String value);

} // StructDeclaration
