/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tuple Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.TupleDeclaration#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getTupleDeclaration()
 * @model
 * @generated
 */
public interface TupleDeclaration extends AbstractCollection
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link com.btc.serviceidl.idl.AbstractType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see com.btc.serviceidl.idl.IdlPackage#getTupleDeclaration_Types()
   * @model containment="true"
   * @generated
   */
  EList<AbstractType> getTypes();

} // TupleDeclaration
