/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Typical Length Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.TypicalLengthHint#getLength <em>Length</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getTypicalLengthHint()
 * @model
 * @generated
 */
public interface TypicalLengthHint extends AbstractSequenceHint
{
  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Length</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see com.btc.serviceidl.idl.IdlPackage#getTypicalLengthHint_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.TypicalLengthHint#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

} // TypicalLengthHint
