/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Typical Size Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.TypicalSizeHint#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see com.btc.serviceidl.idl.IdlPackage#getTypicalSizeHint()
 * @model
 * @generated
 */
public interface TypicalSizeHint extends AbstractSequenceHint
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see com.btc.serviceidl.idl.IdlPackage#getTypicalSizeHint_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link com.btc.serviceidl.idl.TypicalSizeHint#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // TypicalSizeHint
