/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ide;

import com.btc.serviceidl.ide.AbstractIdlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IdlIdeModule extends AbstractIdlIdeModule {
}
