/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.validation;

import com.btc.serviceidl.validation.AbstractIdlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IdlValidator extends AbstractIdlValidator {
}
