/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ui.contentassist;

import com.btc.serviceidl.ui.contentassist.AbstractIdlProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IdlProposalProvider extends AbstractIdlProposalProvider {
}
