/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.scoping;

import com.btc.serviceidl.scoping.AbstractIdlScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class IdlScopeProvider extends AbstractIdlScopeProvider {
}
