/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ui.tests;

import com.btc.serviceidl.ui.internal.ServiceidlActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IdlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ServiceidlActivator.getInstance().getInjector("com.btc.serviceidl.Idl");
	}

}
