/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ui;

import com.btc.serviceidl.ui.AbstractIdlUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IdlUiModule extends AbstractIdlUiModule {
  public IdlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
