/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IdlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/btc/serviceidl/parser/antlr/internal/InternalIdl.tokens");
	}
}
