/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.parser.antlr;

import com.btc.serviceidl.parser.antlr.internal.InternalIdlParser;
import com.btc.serviceidl.services.IdlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IdlParser extends AbstractAntlrParser {

	@Inject
	private IdlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIdlParser createParser(XtextTokenStream stream) {
		return new InternalIdlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "IDLSpecification";
	}

	public IdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
