/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl.impl;

import com.btc.serviceidl.idl.AbstractSequenceHint;
import com.btc.serviceidl.idl.IdlPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Sequence Hint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractSequenceHintImpl extends MinimalEObjectImpl.Container implements AbstractSequenceHint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractSequenceHintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.ABSTRACT_SEQUENCE_HINT;
  }

} //AbstractSequenceHintImpl
