/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl.impl;

import com.btc.serviceidl.idl.AbstractCrossReference;
import com.btc.serviceidl.idl.IdlPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Cross Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractCrossReferenceImpl extends MinimalEObjectImpl.Container implements AbstractCrossReference
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractCrossReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.ABSTRACT_CROSS_REFERENCE;
  }

} //AbstractCrossReferenceImpl
