/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl.impl;

import com.btc.serviceidl.idl.AbstractModuleComponent;
import com.btc.serviceidl.idl.IdlPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Module Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractModuleComponentImpl extends MinimalEObjectImpl.Container implements AbstractModuleComponent
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractModuleComponentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.ABSTRACT_MODULE_COMPONENT;
  }

} //AbstractModuleComponentImpl
