/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl.impl;

import com.btc.serviceidl.idl.EnumDeclaration;
import com.btc.serviceidl.idl.IdlPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enum Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.impl.EnumDeclarationImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.impl.EnumDeclarationImpl#getContainedIdentifiers <em>Contained Identifiers</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.impl.EnumDeclarationImpl#getDeclarator <em>Declarator</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumDeclarationImpl extends AbstractModuleComponentImpl implements EnumDeclaration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getContainedIdentifiers() <em>Contained Identifiers</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContainedIdentifiers()
   * @generated
   * @ordered
   */
  protected EList<String> containedIdentifiers;

  /**
   * The default value of the '{@link #getDeclarator() <em>Declarator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclarator()
   * @generated
   * @ordered
   */
  protected static final String DECLARATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDeclarator() <em>Declarator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDeclarator()
   * @generated
   * @ordered
   */
  protected String declarator = DECLARATOR_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.ENUM_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.ENUM_DECLARATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getContainedIdentifiers()
  {
    if (containedIdentifiers == null)
    {
      containedIdentifiers = new EDataTypeEList<String>(String.class, this, IdlPackage.ENUM_DECLARATION__CONTAINED_IDENTIFIERS);
    }
    return containedIdentifiers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDeclarator()
  {
    return declarator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDeclarator(String newDeclarator)
  {
    String oldDeclarator = declarator;
    declarator = newDeclarator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IdlPackage.ENUM_DECLARATION__DECLARATOR, oldDeclarator, declarator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IdlPackage.ENUM_DECLARATION__NAME:
        return getName();
      case IdlPackage.ENUM_DECLARATION__CONTAINED_IDENTIFIERS:
        return getContainedIdentifiers();
      case IdlPackage.ENUM_DECLARATION__DECLARATOR:
        return getDeclarator();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IdlPackage.ENUM_DECLARATION__NAME:
        setName((String)newValue);
        return;
      case IdlPackage.ENUM_DECLARATION__CONTAINED_IDENTIFIERS:
        getContainedIdentifiers().clear();
        getContainedIdentifiers().addAll((Collection<? extends String>)newValue);
        return;
      case IdlPackage.ENUM_DECLARATION__DECLARATOR:
        setDeclarator((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.ENUM_DECLARATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IdlPackage.ENUM_DECLARATION__CONTAINED_IDENTIFIERS:
        getContainedIdentifiers().clear();
        return;
      case IdlPackage.ENUM_DECLARATION__DECLARATOR:
        setDeclarator(DECLARATOR_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.ENUM_DECLARATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IdlPackage.ENUM_DECLARATION__CONTAINED_IDENTIFIERS:
        return containedIdentifiers != null && !containedIdentifiers.isEmpty();
      case IdlPackage.ENUM_DECLARATION__DECLARATOR:
        return DECLARATOR_EDEFAULT == null ? declarator != null : !DECLARATOR_EDEFAULT.equals(declarator);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", containedIdentifiers: ");
    result.append(containedIdentifiers);
    result.append(", declarator: ");
    result.append(declarator);
    result.append(')');
    return result.toString();
  }

} //EnumDeclarationImpl
