/**
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.idl.impl;

import com.btc.serviceidl.idl.IDLSpecification;
import com.btc.serviceidl.idl.IdlPackage;
import com.btc.serviceidl.idl.ImportDeclaration;
import com.btc.serviceidl.idl.ModuleDeclaration;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>IDL Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.btc.serviceidl.idl.impl.IDLSpecificationImpl#getImportedEntities <em>Imported Entities</em>}</li>
 *   <li>{@link com.btc.serviceidl.idl.impl.IDLSpecificationImpl#getModules <em>Modules</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IDLSpecificationImpl extends MinimalEObjectImpl.Container implements IDLSpecification
{
  /**
   * The cached value of the '{@link #getImportedEntities() <em>Imported Entities</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportedEntities()
   * @generated
   * @ordered
   */
  protected EList<ImportDeclaration> importedEntities;

  /**
   * The cached value of the '{@link #getModules() <em>Modules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModules()
   * @generated
   * @ordered
   */
  protected EList<ModuleDeclaration> modules;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IDLSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IdlPackage.Literals.IDL_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImportDeclaration> getImportedEntities()
  {
    if (importedEntities == null)
    {
      importedEntities = new EObjectContainmentEList<ImportDeclaration>(ImportDeclaration.class, this, IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES);
    }
    return importedEntities;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ModuleDeclaration> getModules()
  {
    if (modules == null)
    {
      modules = new EObjectContainmentEList<ModuleDeclaration>(ModuleDeclaration.class, this, IdlPackage.IDL_SPECIFICATION__MODULES);
    }
    return modules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES:
        return ((InternalEList<?>)getImportedEntities()).basicRemove(otherEnd, msgs);
      case IdlPackage.IDL_SPECIFICATION__MODULES:
        return ((InternalEList<?>)getModules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES:
        return getImportedEntities();
      case IdlPackage.IDL_SPECIFICATION__MODULES:
        return getModules();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES:
        getImportedEntities().clear();
        getImportedEntities().addAll((Collection<? extends ImportDeclaration>)newValue);
        return;
      case IdlPackage.IDL_SPECIFICATION__MODULES:
        getModules().clear();
        getModules().addAll((Collection<? extends ModuleDeclaration>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES:
        getImportedEntities().clear();
        return;
      case IdlPackage.IDL_SPECIFICATION__MODULES:
        getModules().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IdlPackage.IDL_SPECIFICATION__IMPORTED_ENTITIES:
        return importedEntities != null && !importedEntities.isEmpty();
      case IdlPackage.IDL_SPECIFICATION__MODULES:
        return modules != null && !modules.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IDLSpecificationImpl
