/*
 * generated by Xtext 2.13.0
 */
package com.btc.serviceidl.ui;

import com.btc.serviceidl.ui.internal.ServiceidlActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IdlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ServiceidlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ServiceidlActivator activator = ServiceidlActivator.getInstance();
		return activator != null ? activator.getInjector(ServiceidlActivator.COM_BTC_SERVICEIDL_IDL) : null;
	}

}
